### ISSUE TITLE
Process Queue can't get trackalbum with iTunes 9

### ISSUE THREAD

**Issue by StephanieM** [liyanage/album-artwork-assistant#2]
Hi: I've lost the original text of my post as it was submitted through your web form; however the gist is as follows:

With Snow Leopard and iTunes 9, I can add album art only if I add it immediately (i.e. not via add to queue). When using Process Queue, I get things like:  Unable to add album artwork / Can’t get trackContainerId of {trackalbum:"Best of the Classics - Gershwin", trackid:7542}. I don't recall this problem with earlier versions of iTunes or Mac OS X but I'm a very infrequent user of AAA.

**Comment by drewster** [comment]
I would be a frequent user of AAA, except...
I have the same problem and the same error message (Snow Leopard).
Also, when using Add Immediately, I always get the following error message:
"Unable to set album artwork. Parameter error."

So, I cannot use either method to add artwork to iTunes.

Also, confirming that QuickLook does not work.

Thanks in advance Marc for fixing these issues.

**Comment by liyanage** [comment]
fixed in 5cfb7d8c0e2642dc3d0048b3db0323d344e79c53

**Comment by drewster** [comment]
Thanks Marc!

When do you think v2.7 will be available? I downloaded "v2.7" from the link at the top of the page. It didn't contain the 2.7 version of the application, though there were a number of other files that I don't know what to do with.

Andrew

**Comment by liyanage** [comment]
Hi Andrew, check here: http://twitter.com/liyanage/status/5414829441

Before I push it out via auto update I wanted some testing first :-)

**Comment by drewster** [comment]
I tried the new version. No change though -- Quick Look doesn't work for me, and I still get the same error messages described above when I try to Add Immediately and Process Queue.

**Comment by liyanage** [comment]
I forgot to mention, this particular version does _not_ yet fix Quick Look, only the queue execution.

It's really strange that the queue doesn't work for you, it does for me in this version on Mac OS X 10.6.1 / iTunes 9.0.2 (25).
